
export var CONSTANTS = {
    PORT: process.env.PORT,
    DB_USERNAME: process.env.DB_USERNAME,
    DB_PASSWORD: process.env.DB_PASSWORD,
    DB_CLUSTER: process.env.DB_CLUSTER,
    DB_DATABASE: process.env.DB_DATABASE,
    NODEMAILER_OUTLOOK_USERNAME: process.env.NODEMAILER_OUTLOOK_USERNAME,
    NODEMAILER_OUTLOOK_PASSWORD: process.env.NODEMAILER_OUTLOOK_PASSWORD
}